# Generated by Django 2.2 on 2020-04-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eps', '0002_auto_20200412_1519'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=200)),
                ('indicaciones', models.CharField(max_length=250)),
                ('precio', models.FloatField()),
                ('ordenesMedicas', models.ManyToManyField(to='eps.OrdenMedica')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=100)),
                ('precioTotal', models.FloatField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoPedido',
            fields=[
                ('cantidad', models.SmallIntegerField()),
                ('precioTotal', models.FloatField()),
                ('medicamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medicamentos.Medicamento')),
                ('pedido', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Pedido')),
            ],
        ),
    ]
