# Generated by Django 2.2 on 2020-04-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='ordenesMedicas',
        ),
    ]
