# Generated by Django 2.2 on 2020-04-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_remove_medicamento_ordenesmedicas'),
        ('eps', '0002_auto_20200412_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmedica',
            name='medicamentos',
            field=models.ManyToManyField(to='medicamentos.Medicamento'),
        ),
    ]
