# Generated by Django 2.2 on 2020-04-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
                ('edad', models.IntegerField()),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eps.Eps')),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
                ('regMedico', models.CharField(max_length=100)),
                ('edad', models.SmallIntegerField()),
                ('especialidad', models.CharField(max_length=120)),
                ('eps', models.ManyToManyField(to='eps.Eps')),
            ],
            bases=('usuarios.usuario',),
        ),
    ]
