# Generated by Django 2.2 on 2020-04-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_auto_20200412_2300'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='apellidoMedico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='nombreMedico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OrdenMedicaMedico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('uso', models.CharField(blank=True, max_length=120, null=True)),
                ('indicaciones', models.CharField(blank=True, max_length=120, null=True)),
                ('cantidad', models.SmallIntegerField(blank=True, null=True)),
                ('duracion', models.CharField(blank=True, max_length=120, null=True)),
                ('medicamentoAsociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Medicamento')),
                ('medicoAsociaco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Medico')),
                ('pacienteAsociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente')),
            ],
            bases=('usuarios.usuario',),
        ),
    ]
