# Generated by Django 2.2 on 2020-04-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_medico_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='apellidoMedico',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nombreMedico',
        ),
    ]
